// <auto-generated />
using System;
using CodingAssistant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodingAssistant.Infrastructure.Migrations
{
    [DbContext(typeof(CodingAssistantDbContext))]
    [Migration("20260506101700_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodingAssistant.Domain.Entities.AgentMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("ProjectGenerationId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_generation_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_agent_messages");

                    b.HasIndex("ProjectGenerationId", "CreatedAtUtc")
                        .HasDatabaseName("ix_agent_messages_project_generation_id_created_at_utc");

                    b.ToTable("agent_messages", (string)null);
                });

            modelBuilder.Entity("CodingAssistant.Domain.Entities.GeneratedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Language")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("language");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("ProjectGenerationId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_generation_id");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("relative_path");

                    b.HasKey("Id")
                        .HasName("pk_generated_files");

                    b.HasIndex("ProjectGenerationId", "RelativePath")
                        .IsUnique()
                        .HasDatabaseName("ix_generated_files_project_generation_id_relative_path");

                    b.ToTable("generated_files", (string)null);
                });

            modelBuilder.Entity("CodingAssistant.Domain.Entities.GenerationStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AgentRole")
                        .HasColumnType("integer")
                        .HasColumnName("agent_role");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("ProjectGenerationId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_generation_id");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_generation_steps");

                    b.HasIndex("ProjectGenerationId", "Order")
                        .HasDatabaseName("ix_generation_steps_project_generation_id_order");

                    b.ToTable("generation_steps", (string)null);
                });

            modelBuilder.Entity("CodingAssistant.Domain.Entities.ProjectGeneration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("project_name");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TargetStack")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_stack");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("user_prompt");

                    b.HasKey("Id")
                        .HasName("pk_project_generations");

                    b.ToTable("project_generations", (string)null);
                });

            modelBuilder.Entity("CodingAssistant.Domain.Entities.AgentMessage", b =>
                {
                    b.HasOne("CodingAssistant.Domain.Entities.ProjectGeneration", "ProjectGeneration")
                        .WithMany("Messages")
                        .HasForeignKey("ProjectGenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_messages_project_generations_project_generation_id");

                    b.Navigation("ProjectGeneration");
                });

            modelBuilder.Entity("CodingAssistant.Domain.Entities.GeneratedFile", b =>
                {
                    b.HasOne("CodingAssistant.Domain.Entities.ProjectGeneration", "ProjectGeneration")
                        .WithMany("Files")
                        .HasForeignKey("ProjectGenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generated_files_project_generations_project_generation_id");

                    b.Navigation("ProjectGeneration");
                });

            modelBuilder.Entity("CodingAssistant.Domain.Entities.GenerationStep", b =>
                {
                    b.HasOne("CodingAssistant.Domain.Entities.ProjectGeneration", "ProjectGeneration")
                        .WithMany("Steps")
                        .HasForeignKey("ProjectGenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_generation_steps_project_generations_project_generation_id");

                    b.Navigation("ProjectGeneration");
                });

            modelBuilder.Entity("CodingAssistant.Domain.Entities.ProjectGeneration", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Messages");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
