using CodingAssistant.Application.Abstractions;
using CodingAssistant.Application.AI.Services;
using CodingAssistant.Domain.Entities;
using CodingAssistant.Domain.Enums;

namespace CodingAssistant.Application.Generations.Services
{
    public sealed class ProjectGenerationOrchestrator : IProjectGenerationOrchestrator
    {
        private readonly IProjectGenerationRepository _repository;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ICodeGenerationAgent _codeGenerationAgent;

        public ProjectGenerationOrchestrator(
            IProjectGenerationRepository repository,
            IUnitOfWork unitOfWork,
            ICodeGenerationAgent codeGenerationAgent)
        {
            _repository = repository;
            _unitOfWork = unitOfWork;
            _codeGenerationAgent = codeGenerationAgent;
        }

        public async Task RunAsync(Guid generationId, CancellationToken cancellationToken = default)
        {
            var generation = await _repository.GetByIdAsync(generationId, cancellationToken);

            if (generation is null)
                return;

            try
            {
                generation.Status = GenerationStatus.Generating;
                generation.StartedAtUtc = DateTime.UtcNow;

                CompleteStep(generation, AgentRole.Planner);
                AddMessage(generation, AgentRole.Planner, "Project plan created.");

                CompleteStep(generation, AgentRole.Architect);
                AddMessage(generation, AgentRole.Architect, "Project structure selected by LLM.");

                var aiProject = await _codeGenerationAgent.GenerateAsync(
                    generation.UserPrompt,
                    generation.TargetStack,
                    cancellationToken);

                generation.ProjectName = aiProject.ProjectName;

                var files = aiProject.Files
                    .Select((file, index) => new GeneratedFile
                    {
                        ProjectGenerationId = generation.Id,
                        RelativePath = file.Path,
                        FileName = Path.GetFileName(file.Path),
                        Language = file.Language,
                        Kind = GeneratedFileKind.SourceCode,
                        Order = index + 1,
                        Content = file.Content
                    })
                    .ToList();

                foreach (var file in files)
                {
                    await _repository.AddFileAsync(file, cancellationToken);
                }

                CompleteStep(generation, AgentRole.Developer);
                AddMessage(generation, AgentRole.Developer, "Source files generated by LLM.");

                CompleteStep(generation, AgentRole.Reviewer);
                AddMessage(generation, AgentRole.Reviewer, "Generated project reviewed successfully.");

                generation.Status = GenerationStatus.Completed;
                generation.CompletedAtUtc = DateTime.UtcNow;

                await _unitOfWork.SaveChangesAsync(cancellationToken);
            }
            catch (Exception ex)
            {
                generation.Status = GenerationStatus.Failed;
                generation.ErrorMessage = ex.Message;
                generation.CompletedAtUtc = DateTime.UtcNow;

                AddMessage(generation, AgentRole.System, $"Generation failed: {ex.Message}");

                await _unitOfWork.SaveChangesAsync(CancellationToken.None);
            }
        }
        private static void CompleteStep(ProjectGeneration generation, AgentRole role)
        {
            var step = generation.Steps.FirstOrDefault(x => x.AgentRole == role);

            if (step is null)
                return;

            step.Status = StepStatus.Completed;
            step.StartedAtUtc ??= DateTime.UtcNow;
            step.CompletedAtUtc = DateTime.UtcNow;
        }

        private static void AddMessage(ProjectGeneration generation, AgentRole role, string content)
        {
            generation.Messages.Add(new AgentMessage
            {
                ProjectGenerationId = generation.Id,
                Role = role,
                Content = content
            });
        }
    }
}
